export const SIGNIN_INIT_LOADING_DONE = `SIGNIN_INIT_LOADING_DONE`

export const SIGNIN_START = `SIGNIN_START`
export const SIGNIN_SUCCESS = `SIGNIN_SUCCESS`
export const SIGNIN_ERROR = `SIGNIN_ERROR`


export const JOINROOM_START = `JOINROOM_START`
export const JOINROOM_SUCCESS = `JOINROOM_SUCCESS`
export const JOINROOM_ERROR = `JOINROOM_ERROR`

export const ERROR_MESSAGE_CLEAR = `SIGNIN_ERROR_MESSAGE_CLEAR`
